Traceback (most recent call last):
  File "/veracruz/projects/c/cquant/Dirac-Quantum-Walk/QuantumWalk/main.py", line 58, in <module>
    exec_answers = execute_circuits(all_results,
  File "/veracruz/projects/c/cquant/Dirac-Quantum-Walk/QuantumWalk/execute_circuits.py", line 83, in execute_circuits
    answer = job_statevector.result().get_counts()
  File "/veracruz/home/d/dgoncalves/.local/lib/python3.8/site-packages/qiskit_aer/jobs/utils.py", line 42, in _wrapper
    return func(self, *args, **kwargs)
  File "/veracruz/home/d/dgoncalves/.local/lib/python3.8/site-packages/qiskit_aer/jobs/aerjob.py", line 114, in result
    return self._future.result(timeout=timeout)
  File "/apps/software/Anaconda/2020.11/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/apps/software/Anaconda/2020.11/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/apps/software/Anaconda/2020.11/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/veracruz/home/d/dgoncalves/.local/lib/python3.8/site-packages/qiskit_aer/backends/aerbackend.py", line 442, in _execute_circuits_job
    output = self._execute_circuits(aer_circuits, noise_model, config)
  File "/veracruz/home/d/dgoncalves/.local/lib/python3.8/site-packages/qiskit_aer/backends/aer_simulator.py", line 835, in _execute_circuits
    ret = cpp_execute_circuits(self._controller, aer_circuits, noise_model, config)
  File "/veracruz/home/d/dgoncalves/.local/lib/python3.8/site-packages/qiskit_aer/backends/backend_utils.py", line 435, in cpp_execute_circuits
    return controller.execute(aer_circuits, noise_model, config)
RuntimeError: Simulation device "GPU" is not supported on this system
